@ManagementSys.Orders.Commands.Api_HostAddress = http://localhost:5091

GET {{ManagementSys.Orders.Commands.Api_HostAddress}}/todos/
Accept: application/json

###

GET {{ManagementSys.Orders.Commands.Api_HostAddress}}/todos/1
Accept: application/json

###
