@ManagementSys.Orders.Queries.Api_HostAddress = http://localhost:5190

GET {{ManagementSys.Orders.Queries.Api_HostAddress}}/todos/
Accept: application/json

###

GET {{ManagementSys.Orders.Queries.Api_HostAddress}}/todos/1
Accept: application/json

###
